/**
 * User serivce API
 * User service api
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface TokenPayloadDto {
  access_token: string;
  login: string;
  username: string;
  id: string;
}
